// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eepnifeetdqajqheihci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlcG5pZmVldGRxYWpxaGVpaGNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNDA2NzYsImV4cCI6MjA2NTkxNjY3Nn0.ZVZ6L529SYPhQu43pDFFGNcxs62gJmtGthKOGWPC610";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);